### ISSUE TITLE
npm run dev failed

### ISSUE THREAD

**Issue by guanxudong** [Metnew/vue-element-starter#2]
``` ERROR  Failed to compile with 1 errors                                                                 

This relative module was not found:

* ../../theme/fonts/element-icons.eot in ./~/css-loader?-autoprefixer!./~/postcss-loader!./~/sass-loader/lib/loader.js?sourceMap!./client/styles/index.scss
```

the **element-icons.eot** is  not exist in theme/fonts directory

**Comment by guanxudong** [comment]
it seems element-theme's bug, closed

**Comment by Metnew** [comment]
Thanks for reporting your issue.
It seems like Element-UI removed .eot font from generated theme folder.
Must be fixed in https://github.com/Metnew/vue-element-starter/commit/4d5e3199b637b8aa95b13127165f1560ba23cbfe.
