### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by coderabsolute** [Metnew/vue-element-starter#3]
Am a newbie to the frontend development. I just came across to this starter project, the dashboard is nice and clean but am wondering how to add the Login page and upon login (mock data maybe) then redirect to this beautiful dashboard? Sorry, if the question is too basic.

**Comment by Metnew** [comment]
Hi, maybe I will provide Login example soon, but I'm not sure. 
You can find Login page example in similar project implemented with [React +Redux here.](https://github.com/Metnew/reatty)

**Comment by coderabsolute** [comment]
Hi, I will try to decode the React and learn how to translate React Code to VueJs. Thanks anyway.
