### ISSUE TITLE
Google chrome and hot-module-replacment

### ISSUE THREAD

**Issue by marko-mlinarevic** [Metnew/vue-element-starter#7]
I get this error in google chrome in console.

```

You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

(unknown) [HMR] connected

__webpack_hmr Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

(unknown) [HMR] connected

```

I get this error only in chrome. I have seen similar problem on stackoverflow

https://stackoverflow.com/questions/41579808/webpack-hmr-neterr-incomplete-chunked-encoding

But I cannot find any kind of timer in webpack files. Can you point me if you had this problem

**Comment by Metnew** [comment]
Hi, can't reproduce your issue. As I understand, you get this warning in dev mode. I got similar issues caused by broken connection between hmr-client and webpack dev server.
